project:
  type: website
  output-dir: _site

website:
  title: "Course Tutorials"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: floating
    contents:
      - text: "Tutorial 01"
        href: tutorials/tutorial_01.qmd

format:
  html:
    toc: false
