project:
  type: website
  output-dir: "docs"

website:
  title: "Course Tutorials"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        menu:
        - text: "Tutorial 1"
          href: tutorials/tutorial_01.qmd
  sidebar:
    style: docked
    contents:
      - text: "Q1 — Make the sum equal 10"
        href: tutorial_01.qmd#q1-make-the-sum-equal-10
      - text: "Q2 — Write a function"
        href: tutorial_01.qmd#q2-write-a-function-using-division
      - text: "Q3 — Draw a histogram"
        href: tutorial_01.qmd#q3-draw-a-histogram

format:
  live-html:
    toc: false

