project:
  type: website
  output-dir: "docs"

website:
  title: "Course Tutorials"
  site-url: https://nishanmudalige.github.io/STA258_Tutorials/
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: https://nishanmudalige.github.io/STA258_Tutorials/
      - text: "Tutorials"
        menu:
        - text: "Tutorial 1"
          href: tutorials/tutorial_01.qmd
        - text: "Tutorial 2"
          href: tutorials/tutorial_02.qmd
        - text: "Tutorial 3"
          href: tutorials/tutorial_03.qmd
        - text: "Tutorial 4"
          href: tutorials/tutorial_04.qmd
        - text: "Tutorial 5"
          href: tutorials/tutorial_05.qmd
        - text: "Tutorial 6"
          href: tutorials/tutorial_06.qmd
        - text: "Tutorial 7"
          href: tutorials/tutorial_07.qmd
        - text: "Tutorial 8"
          href: tutorials/tutorial_08.qmd
        - text: "Tutorial 9"
          href: tutorials/tutorial_09.qmd
        - text: "Tutorial 10"
          href: tutorials/tutorial_10.qmd
        - text: "Tutorial 11"
          href: tutorials/tutorial_11.qmd
      - text: "Practice"
        menu:
        - text: "Practical 1"
          href: practice/prac_01.qmd
      
format:
  live-html:
    theme: 
      light: flatly
      dark: darkly
    css: design.css
    toc: false

